### ISSUE TITLE
Where is the code

### ISSUE THREAD

**Issue by copperstick6** [kathdovi/Word-Guess-Game#2]
NANI?!?!!

**Comment by kathdovi** [comment]
you have to guess them all can't you see it's called word guess game

**Comment by michaelasper** [comment]
at least all the code follows the code style

**Comment by kathdovi** [comment]
is this cyberbullying

**Comment by copperstick6** [comment]
hmm yeah @michaelasper you're right. Also, here's a quick hack for this game: https://www.dictionary.com/
