### ISSUE TITLE
ads are terrible

### ISSUE THREAD

**Issue by copperstick6** [kathdovi/Word-Guess-Game#3]
looks ok on mobile, absolute garbage on desktop
  
~~also: fuck ads, they suck.~~  
uhm ads are great!!!!

**Comment by kathdovi** [comment]
issue #4 william han is destroying my life

i am gonna fill that right side with something ad space is a nice copout

**Comment by copperstick6** [comment]
#5 please.   
thx

**Comment by kathdovi** [comment]
I didn't see 4 when I typed this _please_

**Comment by kathdovi** [comment]
ads can only be disabled with hangman prime.

**Comment by copperstick6** [comment]
Damn capitalists
