### ISSUE TITLE
Consider reading from HangmanMovies.txt

### ISSUE THREAD

**Issue by copperstick6** [kathdovi/Word-Guess-Game#4]
https://github.com/kathdovi/Word-Guess-Game/blob/5829cb13f354c0c7e25001f898c1540a974af188/assets/javascript/game.js#L1

You can just read this in from HangmanMovies.txt using FileReader or fetch afaik

**Comment by kathdovi** [comment]
yeah I tried to do this at the beginning of writing this and things weren't reading but i'm gonna try and make it work again

**Comment by copperstick6** [comment]
fixed in 5e10d722dd380f7db717292772187c738a540970
